/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockwifi_hal_sta.h"

static const char* CMockString_apIndex = "apIndex";
static const char* CMockString_bss = "bss";
static const char* CMockString_callback_proc = "callback_proc";
static const char* CMockString_wifi_connect = "wifi_connect";
static const char* CMockString_wifi_disconnect = "wifi_disconnect";
static const char* CMockString_wifi_staConnectionStatus_callback_register = "wifi_staConnectionStatus_callback_register";

typedef struct _CMOCK_wifi_connect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  INT Expected_apIndex;
  wifi_bss_info_t* Expected_bss;

} CMOCK_wifi_connect_CALL_INSTANCE;

typedef struct _CMOCK_wifi_disconnect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  INT Expected_apIndex;

} CMOCK_wifi_disconnect_CALL_INSTANCE;

typedef struct _CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  wifi_staConnectionStatus_callback Expected_callback_proc;

} CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE;

static struct Mockwifi_hal_staInstance
{
  CMOCK_MEM_INDEX_TYPE wifi_connect_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_disconnect_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_staConnectionStatus_callback_register_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockwifi_hal_sta_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.wifi_connect_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_connect);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_disconnect_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_disconnect);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_staConnectionStatus_callback_register_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_staConnectionStatus_callback_register);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockwifi_hal_sta_Init(void)
{
  Mockwifi_hal_sta_Destroy();
}

void Mockwifi_hal_sta_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

INT wifi_connect(INT apIndex, wifi_bss_info_t* bss)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_connect_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_connect);
  cmock_call_instance = (CMOCK_wifi_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_connect_CallInstance);
  Mock.wifi_connect_CallInstance = CMock_Guts_MemNext(Mock.wifi_connect_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_connect,CMockString_apIndex);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex), sizeof(INT), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_connect,CMockString_bss);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_bss), (void*)(bss), sizeof(wifi_bss_info_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_connect(CMOCK_wifi_connect_CALL_INSTANCE* cmock_call_instance, INT apIndex, wifi_bss_info_t* bss);
void CMockExpectParameters_wifi_connect(CMOCK_wifi_connect_CALL_INSTANCE* cmock_call_instance, INT apIndex, wifi_bss_info_t* bss)
{
  memcpy((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex),
         sizeof(INT[sizeof(apIndex) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_bss = bss;
}

void wifi_connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, wifi_bss_info_t* bss, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_connect_CALL_INSTANCE));
  CMOCK_wifi_connect_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_connect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_connect_CallInstance = CMock_Guts_MemChain(Mock.wifi_connect_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_connect(cmock_call_instance, apIndex, bss);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_disconnect(INT apIndex)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_disconnect_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_disconnect);
  cmock_call_instance = (CMOCK_wifi_disconnect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_disconnect_CallInstance);
  Mock.wifi_disconnect_CallInstance = CMock_Guts_MemNext(Mock.wifi_disconnect_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_disconnect,CMockString_apIndex);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex), sizeof(INT), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_disconnect(CMOCK_wifi_disconnect_CALL_INSTANCE* cmock_call_instance, INT apIndex);
void CMockExpectParameters_wifi_disconnect(CMOCK_wifi_disconnect_CALL_INSTANCE* cmock_call_instance, INT apIndex)
{
  memcpy((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex),
         sizeof(INT[sizeof(apIndex) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

void wifi_disconnect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_disconnect_CALL_INSTANCE));
  CMOCK_wifi_disconnect_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_disconnect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_disconnect_CallInstance = CMock_Guts_MemChain(Mock.wifi_disconnect_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_disconnect(cmock_call_instance, apIndex);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

void wifi_staConnectionStatus_callback_register(wifi_staConnectionStatus_callback callback_proc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_staConnectionStatus_callback_register);
  cmock_call_instance = (CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_staConnectionStatus_callback_register_CallInstance);
  Mock.wifi_staConnectionStatus_callback_register_CallInstance = CMock_Guts_MemNext(Mock.wifi_staConnectionStatus_callback_register_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_staConnectionStatus_callback_register,CMockString_callback_proc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc), sizeof(wifi_staConnectionStatus_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_wifi_staConnectionStatus_callback_register(CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_staConnectionStatus_callback callback_proc);
void CMockExpectParameters_wifi_staConnectionStatus_callback_register(CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_staConnectionStatus_callback callback_proc)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc),
         sizeof(wifi_staConnectionStatus_callback[sizeof(callback_proc) == sizeof(wifi_staConnectionStatus_callback) ? 1 : -1])); /* add wifi_staConnectionStatus_callback to :treat_as_array if this causes an error */
}

void wifi_staConnectionStatus_callback_register_CMockExpect(UNITY_LINE_TYPE cmock_line, wifi_staConnectionStatus_callback callback_proc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE));
  CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_staConnectionStatus_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_staConnectionStatus_callback_register_CallInstance = CMock_Guts_MemChain(Mock.wifi_staConnectionStatus_callback_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_staConnectionStatus_callback_register(cmock_call_instance, callback_proc);
}

