/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockwifi_hal_generic.h"

static const char* CMockString_cap = "cap";
static const char* CMockString_wifi_getHalCapability = "wifi_getHalCapability";
static const char* CMockString_wifi_init = "wifi_init";

typedef struct _CMOCK_wifi_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;

} CMOCK_wifi_init_CALL_INSTANCE;

typedef struct _CMOCK_wifi_getHalCapability_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  wifi_hal_capability_t* Expected_cap;

} CMOCK_wifi_getHalCapability_CALL_INSTANCE;

static struct Mockwifi_hal_genericInstance
{
  CMOCK_MEM_INDEX_TYPE wifi_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_getHalCapability_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockwifi_hal_generic_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.wifi_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_getHalCapability_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_getHalCapability);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockwifi_hal_generic_Init(void)
{
  Mockwifi_hal_generic_Destroy();
}

void Mockwifi_hal_generic_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

INT wifi_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_init);
  cmock_call_instance = (CMOCK_wifi_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_init_CallInstance);
  Mock.wifi_init_CallInstance = CMock_Guts_MemNext(Mock.wifi_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void wifi_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_init_CALL_INSTANCE));
  CMOCK_wifi_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_init_CallInstance = CMock_Guts_MemChain(Mock.wifi_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_getHalCapability(wifi_hal_capability_t* cap)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_getHalCapability_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_getHalCapability);
  cmock_call_instance = (CMOCK_wifi_getHalCapability_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_getHalCapability_CallInstance);
  Mock.wifi_getHalCapability_CallInstance = CMock_Guts_MemNext(Mock.wifi_getHalCapability_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_getHalCapability,CMockString_cap);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cap), (void*)(cap), sizeof(wifi_hal_capability_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_getHalCapability(CMOCK_wifi_getHalCapability_CALL_INSTANCE* cmock_call_instance, wifi_hal_capability_t* cap);
void CMockExpectParameters_wifi_getHalCapability(CMOCK_wifi_getHalCapability_CALL_INSTANCE* cmock_call_instance, wifi_hal_capability_t* cap)
{
  cmock_call_instance->Expected_cap = cap;
}

void wifi_getHalCapability_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, wifi_hal_capability_t* cap, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_getHalCapability_CALL_INSTANCE));
  CMOCK_wifi_getHalCapability_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_getHalCapability_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_getHalCapability_CallInstance = CMock_Guts_MemChain(Mock.wifi_getHalCapability_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_getHalCapability(cmock_call_instance, cap);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

