/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockwifi_hal_ap.h"

static const char* CMockString_apIndex = "apIndex";
static const char* CMockString_callback_proc = "callback_proc";
static const char* CMockString_enable = "enable";
static const char* CMockString_index = "index";
static const char* CMockString_map = "map";
static const char* CMockString_maxNumDevices = "maxNumDevices";
static const char* CMockString_mgmtRxCallback = "mgmtRxCallback";
static const char* CMockString_output_deviceMacAddressArray = "output_deviceMacAddressArray";
static const char* CMockString_output_numDevices = "output_numDevices";
static const char* CMockString_sta = "sta";
static const char* CMockString_wifi_apDeAuthEvent_callback_register = "wifi_apDeAuthEvent_callback_register";
static const char* CMockString_wifi_apDisassociatedDevice_callback_register = "wifi_apDisassociatedDevice_callback_register";
static const char* CMockString_wifi_createVAP = "wifi_createVAP";
static const char* CMockString_wifi_enableCSIEngine = "wifi_enableCSIEngine";
static const char* CMockString_wifi_getApAssociatedDevice = "wifi_getApAssociatedDevice";
static const char* CMockString_wifi_getRadioVapInfoMap = "wifi_getRadioVapInfoMap";
static const char* CMockString_wifi_mgmt_frame_callbacks_register = "wifi_mgmt_frame_callbacks_register";
static const char* CMockString_wifi_newApAssociatedDevice_callback_register = "wifi_newApAssociatedDevice_callback_register";

typedef struct _CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  INT Expected_apIndex;
  mac_address_t* Expected_output_deviceMacAddressArray;
  UINT Expected_maxNumDevices;
  UINT* Expected_output_numDevices;

} CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE;

typedef struct _CMOCK_wifi_enableCSIEngine_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  INT Expected_apIndex;
  mac_address_t Expected_sta;
  BOOL Expected_enable;

} CMOCK_wifi_enableCSIEngine_CALL_INSTANCE;

typedef struct _CMOCK_wifi_createVAP_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  wifi_radio_index_t Expected_index;
  wifi_vap_info_map_t* Expected_map;

} CMOCK_wifi_createVAP_CALL_INSTANCE;

typedef struct _CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  wifi_radio_index_t Expected_index;
  wifi_vap_info_map_t* Expected_map;

} CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE;

typedef struct _CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  wifi_receivedMgmtFrame_callback Expected_mgmtRxCallback;

} CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE;

typedef struct _CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  wifi_newApAssociatedDevice_callback Expected_callback_proc;

} CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE;

typedef struct _CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  wifi_apDeAuthEvent_callback Expected_callback_proc;

} CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE;

typedef struct _CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  wifi_apDisassociatedDevice_callback Expected_callback_proc;

} CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE;

static struct Mockwifi_hal_apInstance
{
  CMOCK_MEM_INDEX_TYPE wifi_getApAssociatedDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_enableCSIEngine_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_createVAP_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_getRadioVapInfoMap_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_mgmt_frame_callbacks_register_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_newApAssociatedDevice_callback_register_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_apDeAuthEvent_callback_register_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_apDisassociatedDevice_callback_register_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockwifi_hal_ap_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.wifi_getApAssociatedDevice_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_getApAssociatedDevice);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_enableCSIEngine_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_enableCSIEngine);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_createVAP_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_createVAP);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_getRadioVapInfoMap_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_getRadioVapInfoMap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_mgmt_frame_callbacks_register_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_mgmt_frame_callbacks_register);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_newApAssociatedDevice_callback_register_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_newApAssociatedDevice_callback_register);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_apDeAuthEvent_callback_register_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_apDeAuthEvent_callback_register);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_apDisassociatedDevice_callback_register_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_apDisassociatedDevice_callback_register);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockwifi_hal_ap_Init(void)
{
  Mockwifi_hal_ap_Destroy();
}

void Mockwifi_hal_ap_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

INT wifi_getApAssociatedDevice(INT apIndex, mac_address_t* output_deviceMacAddressArray, UINT maxNumDevices, UINT* output_numDevices)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_getApAssociatedDevice);
  cmock_call_instance = (CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_getApAssociatedDevice_CallInstance);
  Mock.wifi_getApAssociatedDevice_CallInstance = CMock_Guts_MemNext(Mock.wifi_getApAssociatedDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_getApAssociatedDevice,CMockString_apIndex);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex), sizeof(INT), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_getApAssociatedDevice,CMockString_output_deviceMacAddressArray);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_output_deviceMacAddressArray), (void*)(output_deviceMacAddressArray), sizeof(mac_address_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_getApAssociatedDevice,CMockString_maxNumDevices);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_maxNumDevices), (void*)(&maxNumDevices), sizeof(UINT), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_getApAssociatedDevice,CMockString_output_numDevices);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_output_numDevices), (void*)(output_numDevices), sizeof(UINT), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_getApAssociatedDevice(CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE* cmock_call_instance, INT apIndex, mac_address_t* output_deviceMacAddressArray, UINT maxNumDevices, UINT* output_numDevices);
void CMockExpectParameters_wifi_getApAssociatedDevice(CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE* cmock_call_instance, INT apIndex, mac_address_t* output_deviceMacAddressArray, UINT maxNumDevices, UINT* output_numDevices)
{
  memcpy((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex),
         sizeof(INT[sizeof(apIndex) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_output_deviceMacAddressArray = output_deviceMacAddressArray;
  memcpy((void*)(&cmock_call_instance->Expected_maxNumDevices), (void*)(&maxNumDevices),
         sizeof(UINT[sizeof(maxNumDevices) == sizeof(UINT) ? 1 : -1])); /* add UINT to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_output_numDevices = output_numDevices;
}

void wifi_getApAssociatedDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, mac_address_t* output_deviceMacAddressArray, UINT maxNumDevices, UINT* output_numDevices, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE));
  CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_getApAssociatedDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_getApAssociatedDevice_CallInstance = CMock_Guts_MemChain(Mock.wifi_getApAssociatedDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_getApAssociatedDevice(cmock_call_instance, apIndex, output_deviceMacAddressArray, maxNumDevices, output_numDevices);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_enableCSIEngine(INT apIndex, mac_address_t sta, BOOL enable)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_enableCSIEngine_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_enableCSIEngine);
  cmock_call_instance = (CMOCK_wifi_enableCSIEngine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_enableCSIEngine_CallInstance);
  Mock.wifi_enableCSIEngine_CallInstance = CMock_Guts_MemNext(Mock.wifi_enableCSIEngine_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_enableCSIEngine,CMockString_apIndex);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex), sizeof(INT), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_enableCSIEngine,CMockString_sta);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sta), (void*)(&sta), sizeof(mac_address_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_enableCSIEngine,CMockString_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enable, enable, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_enableCSIEngine(CMOCK_wifi_enableCSIEngine_CALL_INSTANCE* cmock_call_instance, INT apIndex, mac_address_t sta, BOOL enable);
void CMockExpectParameters_wifi_enableCSIEngine(CMOCK_wifi_enableCSIEngine_CALL_INSTANCE* cmock_call_instance, INT apIndex, mac_address_t sta, BOOL enable)
{
  memcpy((void*)(&cmock_call_instance->Expected_apIndex), (void*)(&apIndex),
         sizeof(INT[sizeof(apIndex) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_sta), (void*)(&sta),
         sizeof(mac_address_t[sizeof(sta) == sizeof(mac_address_t) ? 1 : -1])); /* add mac_address_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_enable = enable;
}

void wifi_enableCSIEngine_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, mac_address_t sta, BOOL enable, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_enableCSIEngine_CALL_INSTANCE));
  CMOCK_wifi_enableCSIEngine_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_enableCSIEngine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_enableCSIEngine_CallInstance = CMock_Guts_MemChain(Mock.wifi_enableCSIEngine_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_enableCSIEngine(cmock_call_instance, apIndex, sta, enable);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_createVAP(wifi_radio_index_t index, wifi_vap_info_map_t* map)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_createVAP_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_createVAP);
  cmock_call_instance = (CMOCK_wifi_createVAP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_createVAP_CallInstance);
  Mock.wifi_createVAP_CallInstance = CMock_Guts_MemNext(Mock.wifi_createVAP_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_createVAP,CMockString_index);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_index), (void*)(&index), sizeof(wifi_radio_index_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_createVAP,CMockString_map);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_map), (void*)(map), sizeof(wifi_vap_info_map_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_createVAP(CMOCK_wifi_createVAP_CALL_INSTANCE* cmock_call_instance, wifi_radio_index_t index, wifi_vap_info_map_t* map);
void CMockExpectParameters_wifi_createVAP(CMOCK_wifi_createVAP_CALL_INSTANCE* cmock_call_instance, wifi_radio_index_t index, wifi_vap_info_map_t* map)
{
  memcpy((void*)(&cmock_call_instance->Expected_index), (void*)(&index),
         sizeof(wifi_radio_index_t[sizeof(index) == sizeof(wifi_radio_index_t) ? 1 : -1])); /* add wifi_radio_index_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_map = map;
}

void wifi_createVAP_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, wifi_radio_index_t index, wifi_vap_info_map_t* map, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_createVAP_CALL_INSTANCE));
  CMOCK_wifi_createVAP_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_createVAP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_createVAP_CallInstance = CMock_Guts_MemChain(Mock.wifi_createVAP_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_createVAP(cmock_call_instance, index, map);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_getRadioVapInfoMap(wifi_radio_index_t index, wifi_vap_info_map_t* map)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_getRadioVapInfoMap);
  cmock_call_instance = (CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_getRadioVapInfoMap_CallInstance);
  Mock.wifi_getRadioVapInfoMap_CallInstance = CMock_Guts_MemNext(Mock.wifi_getRadioVapInfoMap_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_getRadioVapInfoMap,CMockString_index);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_index), (void*)(&index), sizeof(wifi_radio_index_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_getRadioVapInfoMap,CMockString_map);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_map), (void*)(map), sizeof(wifi_vap_info_map_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_getRadioVapInfoMap(CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE* cmock_call_instance, wifi_radio_index_t index, wifi_vap_info_map_t* map);
void CMockExpectParameters_wifi_getRadioVapInfoMap(CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE* cmock_call_instance, wifi_radio_index_t index, wifi_vap_info_map_t* map)
{
  memcpy((void*)(&cmock_call_instance->Expected_index), (void*)(&index),
         sizeof(wifi_radio_index_t[sizeof(index) == sizeof(wifi_radio_index_t) ? 1 : -1])); /* add wifi_radio_index_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_map = map;
}

void wifi_getRadioVapInfoMap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, wifi_radio_index_t index, wifi_vap_info_map_t* map, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE));
  CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_getRadioVapInfoMap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_getRadioVapInfoMap_CallInstance = CMock_Guts_MemChain(Mock.wifi_getRadioVapInfoMap_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_getRadioVapInfoMap(cmock_call_instance, index, map);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_mgmt_frame_callbacks_register(wifi_receivedMgmtFrame_callback mgmtRxCallback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_mgmt_frame_callbacks_register);
  cmock_call_instance = (CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_mgmt_frame_callbacks_register_CallInstance);
  Mock.wifi_mgmt_frame_callbacks_register_CallInstance = CMock_Guts_MemNext(Mock.wifi_mgmt_frame_callbacks_register_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_mgmt_frame_callbacks_register,CMockString_mgmtRxCallback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_mgmtRxCallback), (void*)(&mgmtRxCallback), sizeof(wifi_receivedMgmtFrame_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_mgmt_frame_callbacks_register(CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE* cmock_call_instance, wifi_receivedMgmtFrame_callback mgmtRxCallback);
void CMockExpectParameters_wifi_mgmt_frame_callbacks_register(CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE* cmock_call_instance, wifi_receivedMgmtFrame_callback mgmtRxCallback)
{
  memcpy((void*)(&cmock_call_instance->Expected_mgmtRxCallback), (void*)(&mgmtRxCallback),
         sizeof(wifi_receivedMgmtFrame_callback[sizeof(mgmtRxCallback) == sizeof(wifi_receivedMgmtFrame_callback) ? 1 : -1])); /* add wifi_receivedMgmtFrame_callback to :treat_as_array if this causes an error */
}

void wifi_mgmt_frame_callbacks_register_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, wifi_receivedMgmtFrame_callback mgmtRxCallback, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE));
  CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_mgmt_frame_callbacks_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_mgmt_frame_callbacks_register_CallInstance = CMock_Guts_MemChain(Mock.wifi_mgmt_frame_callbacks_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_mgmt_frame_callbacks_register(cmock_call_instance, mgmtRxCallback);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

void wifi_newApAssociatedDevice_callback_register(wifi_newApAssociatedDevice_callback callback_proc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_newApAssociatedDevice_callback_register);
  cmock_call_instance = (CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_newApAssociatedDevice_callback_register_CallInstance);
  Mock.wifi_newApAssociatedDevice_callback_register_CallInstance = CMock_Guts_MemNext(Mock.wifi_newApAssociatedDevice_callback_register_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_newApAssociatedDevice_callback_register,CMockString_callback_proc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc), sizeof(wifi_newApAssociatedDevice_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_wifi_newApAssociatedDevice_callback_register(CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_newApAssociatedDevice_callback callback_proc);
void CMockExpectParameters_wifi_newApAssociatedDevice_callback_register(CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_newApAssociatedDevice_callback callback_proc)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc),
         sizeof(wifi_newApAssociatedDevice_callback[sizeof(callback_proc) == sizeof(wifi_newApAssociatedDevice_callback) ? 1 : -1])); /* add wifi_newApAssociatedDevice_callback to :treat_as_array if this causes an error */
}

void wifi_newApAssociatedDevice_callback_register_CMockExpect(UNITY_LINE_TYPE cmock_line, wifi_newApAssociatedDevice_callback callback_proc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE));
  CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_newApAssociatedDevice_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_newApAssociatedDevice_callback_register_CallInstance = CMock_Guts_MemChain(Mock.wifi_newApAssociatedDevice_callback_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_newApAssociatedDevice_callback_register(cmock_call_instance, callback_proc);
}

void wifi_apDeAuthEvent_callback_register(wifi_apDeAuthEvent_callback callback_proc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_apDeAuthEvent_callback_register);
  cmock_call_instance = (CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_apDeAuthEvent_callback_register_CallInstance);
  Mock.wifi_apDeAuthEvent_callback_register_CallInstance = CMock_Guts_MemNext(Mock.wifi_apDeAuthEvent_callback_register_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_apDeAuthEvent_callback_register,CMockString_callback_proc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc), sizeof(wifi_apDeAuthEvent_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_wifi_apDeAuthEvent_callback_register(CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_apDeAuthEvent_callback callback_proc);
void CMockExpectParameters_wifi_apDeAuthEvent_callback_register(CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_apDeAuthEvent_callback callback_proc)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc),
         sizeof(wifi_apDeAuthEvent_callback[sizeof(callback_proc) == sizeof(wifi_apDeAuthEvent_callback) ? 1 : -1])); /* add wifi_apDeAuthEvent_callback to :treat_as_array if this causes an error */
}

void wifi_apDeAuthEvent_callback_register_CMockExpect(UNITY_LINE_TYPE cmock_line, wifi_apDeAuthEvent_callback callback_proc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE));
  CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_apDeAuthEvent_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_apDeAuthEvent_callback_register_CallInstance = CMock_Guts_MemChain(Mock.wifi_apDeAuthEvent_callback_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_apDeAuthEvent_callback_register(cmock_call_instance, callback_proc);
}

void wifi_apDisassociatedDevice_callback_register(wifi_apDisassociatedDevice_callback callback_proc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_apDisassociatedDevice_callback_register);
  cmock_call_instance = (CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_apDisassociatedDevice_callback_register_CallInstance);
  Mock.wifi_apDisassociatedDevice_callback_register_CallInstance = CMock_Guts_MemNext(Mock.wifi_apDisassociatedDevice_callback_register_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_apDisassociatedDevice_callback_register,CMockString_callback_proc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc), sizeof(wifi_apDisassociatedDevice_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_wifi_apDisassociatedDevice_callback_register(CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_apDisassociatedDevice_callback callback_proc);
void CMockExpectParameters_wifi_apDisassociatedDevice_callback_register(CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_apDisassociatedDevice_callback callback_proc)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc),
         sizeof(wifi_apDisassociatedDevice_callback[sizeof(callback_proc) == sizeof(wifi_apDisassociatedDevice_callback) ? 1 : -1])); /* add wifi_apDisassociatedDevice_callback to :treat_as_array if this causes an error */
}

void wifi_apDisassociatedDevice_callback_register_CMockExpect(UNITY_LINE_TYPE cmock_line, wifi_apDisassociatedDevice_callback callback_proc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE));
  CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_apDisassociatedDevice_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_apDisassociatedDevice_callback_register_CallInstance = CMock_Guts_MemChain(Mock.wifi_apDisassociatedDevice_callback_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_apDisassociatedDevice_callback_register(cmock_call_instance, callback_proc);
}

