/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockwifi_hal_radio.h"

static const char* CMockString_callback_proc = "callback_proc";
static const char* CMockString_index = "index";
static const char* CMockString_operationParam = "operationParam";
static const char* CMockString_output_string = "output_string";
static const char* CMockString_output_ulong = "output_ulong";
static const char* CMockString_radioIndex = "radioIndex";
static const char* CMockString_wifi_getRadioOperatingChannelBandwidth = "wifi_getRadioOperatingChannelBandwidth";
static const char* CMockString_wifi_getRadioTransmitPower = "wifi_getRadioTransmitPower";
static const char* CMockString_wifi_scanResults_callback_register = "wifi_scanResults_callback_register";
static const char* CMockString_wifi_setRadioOperatingParameters = "wifi_setRadioOperatingParameters";

typedef struct _CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  INT Expected_radioIndex;
  ULONG* Expected_output_ulong;

} CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE;

typedef struct _CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  INT Expected_radioIndex;
  CHAR* Expected_output_string;

} CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE;

typedef struct _CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  INT ReturnVal;
  wifi_radio_index_t Expected_index;
  wifi_radio_operationParam_t* Expected_operationParam;

} CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE;

typedef struct _CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  wifi_scanResults_callback Expected_callback_proc;

} CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE;

static struct Mockwifi_hal_radioInstance
{
  CMOCK_MEM_INDEX_TYPE wifi_getRadioTransmitPower_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_getRadioOperatingChannelBandwidth_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_setRadioOperatingParameters_CallInstance;
  CMOCK_MEM_INDEX_TYPE wifi_scanResults_callback_register_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockwifi_hal_radio_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.wifi_getRadioTransmitPower_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_getRadioTransmitPower);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_getRadioOperatingChannelBandwidth_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_getRadioOperatingChannelBandwidth);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_setRadioOperatingParameters_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_setRadioOperatingParameters);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.wifi_scanResults_callback_register_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_wifi_scanResults_callback_register);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockwifi_hal_radio_Init(void)
{
  Mockwifi_hal_radio_Destroy();
}

void Mockwifi_hal_radio_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

INT wifi_getRadioTransmitPower(INT radioIndex, ULONG* output_ulong)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_getRadioTransmitPower);
  cmock_call_instance = (CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_getRadioTransmitPower_CallInstance);
  Mock.wifi_getRadioTransmitPower_CallInstance = CMock_Guts_MemNext(Mock.wifi_getRadioTransmitPower_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_getRadioTransmitPower,CMockString_radioIndex);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_radioIndex), (void*)(&radioIndex), sizeof(INT), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_getRadioTransmitPower,CMockString_output_ulong);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_output_ulong), (void*)(output_ulong), sizeof(ULONG), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_getRadioTransmitPower(CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE* cmock_call_instance, INT radioIndex, ULONG* output_ulong);
void CMockExpectParameters_wifi_getRadioTransmitPower(CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE* cmock_call_instance, INT radioIndex, ULONG* output_ulong)
{
  memcpy((void*)(&cmock_call_instance->Expected_radioIndex), (void*)(&radioIndex),
         sizeof(INT[sizeof(radioIndex) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_output_ulong = output_ulong;
}

void wifi_getRadioTransmitPower_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT radioIndex, ULONG* output_ulong, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE));
  CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_getRadioTransmitPower_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_getRadioTransmitPower_CallInstance = CMock_Guts_MemChain(Mock.wifi_getRadioTransmitPower_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_getRadioTransmitPower(cmock_call_instance, radioIndex, output_ulong);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_getRadioOperatingChannelBandwidth(INT radioIndex, CHAR* output_string)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_getRadioOperatingChannelBandwidth);
  cmock_call_instance = (CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_getRadioOperatingChannelBandwidth_CallInstance);
  Mock.wifi_getRadioOperatingChannelBandwidth_CallInstance = CMock_Guts_MemNext(Mock.wifi_getRadioOperatingChannelBandwidth_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_getRadioOperatingChannelBandwidth,CMockString_radioIndex);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_radioIndex), (void*)(&radioIndex), sizeof(INT), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_getRadioOperatingChannelBandwidth,CMockString_output_string);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_output_string), (void*)(output_string), sizeof(CHAR), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_getRadioOperatingChannelBandwidth(CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE* cmock_call_instance, INT radioIndex, CHAR* output_string);
void CMockExpectParameters_wifi_getRadioOperatingChannelBandwidth(CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE* cmock_call_instance, INT radioIndex, CHAR* output_string)
{
  memcpy((void*)(&cmock_call_instance->Expected_radioIndex), (void*)(&radioIndex),
         sizeof(INT[sizeof(radioIndex) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_output_string = output_string;
}

void wifi_getRadioOperatingChannelBandwidth_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT radioIndex, CHAR* output_string, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE));
  CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_getRadioOperatingChannelBandwidth_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_getRadioOperatingChannelBandwidth_CallInstance = CMock_Guts_MemChain(Mock.wifi_getRadioOperatingChannelBandwidth_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_getRadioOperatingChannelBandwidth(cmock_call_instance, radioIndex, output_string);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

INT wifi_setRadioOperatingParameters(wifi_radio_index_t index, wifi_radio_operationParam_t* operationParam)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_setRadioOperatingParameters);
  cmock_call_instance = (CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_setRadioOperatingParameters_CallInstance);
  Mock.wifi_setRadioOperatingParameters_CallInstance = CMock_Guts_MemNext(Mock.wifi_setRadioOperatingParameters_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_setRadioOperatingParameters,CMockString_index);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_index), (void*)(&index), sizeof(wifi_radio_index_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_wifi_setRadioOperatingParameters,CMockString_operationParam);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_operationParam), (void*)(operationParam), sizeof(wifi_radio_operationParam_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_wifi_setRadioOperatingParameters(CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE* cmock_call_instance, wifi_radio_index_t index, wifi_radio_operationParam_t* operationParam);
void CMockExpectParameters_wifi_setRadioOperatingParameters(CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE* cmock_call_instance, wifi_radio_index_t index, wifi_radio_operationParam_t* operationParam)
{
  memcpy((void*)(&cmock_call_instance->Expected_index), (void*)(&index),
         sizeof(wifi_radio_index_t[sizeof(index) == sizeof(wifi_radio_index_t) ? 1 : -1])); /* add wifi_radio_index_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_operationParam = operationParam;
}

void wifi_setRadioOperatingParameters_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, wifi_radio_index_t index, wifi_radio_operationParam_t* operationParam, INT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE));
  CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_setRadioOperatingParameters_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_setRadioOperatingParameters_CallInstance = CMock_Guts_MemChain(Mock.wifi_setRadioOperatingParameters_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_setRadioOperatingParameters(cmock_call_instance, index, operationParam);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(INT[sizeof(cmock_to_return) == sizeof(INT) ? 1 : -1])); /* add INT to :treat_as_array if this causes an error */
}

void wifi_scanResults_callback_register(wifi_scanResults_callback callback_proc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_wifi_scanResults_callback_register);
  cmock_call_instance = (CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.wifi_scanResults_callback_register_CallInstance);
  Mock.wifi_scanResults_callback_register_CallInstance = CMock_Guts_MemNext(Mock.wifi_scanResults_callback_register_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_wifi_scanResults_callback_register,CMockString_callback_proc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc), sizeof(wifi_scanResults_callback), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_wifi_scanResults_callback_register(CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_scanResults_callback callback_proc);
void CMockExpectParameters_wifi_scanResults_callback_register(CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE* cmock_call_instance, wifi_scanResults_callback callback_proc)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback_proc), (void*)(&callback_proc),
         sizeof(wifi_scanResults_callback[sizeof(callback_proc) == sizeof(wifi_scanResults_callback) ? 1 : -1])); /* add wifi_scanResults_callback to :treat_as_array if this causes an error */
}

void wifi_scanResults_callback_register_CMockExpect(UNITY_LINE_TYPE cmock_line, wifi_scanResults_callback callback_proc)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE));
  CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_wifi_scanResults_callback_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.wifi_scanResults_callback_register_CallInstance = CMock_Guts_MemChain(Mock.wifi_scanResults_callback_register_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_wifi_scanResults_callback_register(cmock_call_instance, callback_proc);
}

