/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKWIFI_HAL_EXTENDER_H
#define _MOCKWIFI_HAL_EXTENDER_H

#include "unity.h"
#include "wifi_hal_extender.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockwifi_hal_extender_Init(void);
void Mockwifi_hal_extender_Destroy(void);
void Mockwifi_hal_extender_Verify(void);




#define wifi_getRadioChannelStats_ExpectAndReturn(radioIndex, input_output_channelStats_array, array_size, cmock_retval) wifi_getRadioChannelStats_CMockExpectAndReturn(__LINE__, radioIndex, input_output_channelStats_array, array_size, cmock_retval)
void wifi_getRadioChannelStats_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT radioIndex, wifi_channelStats_t* input_output_channelStats_array, INT array_size, INT cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
