/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKWIFI_HAL_STA_H
#define _MOCKWIFI_HAL_STA_H

#include "unity.h"
#include "wifi_hal_sta.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockwifi_hal_sta_Init(void);
void Mockwifi_hal_sta_Destroy(void);
void Mockwifi_hal_sta_Verify(void);




#define wifi_connect_ExpectAndReturn(apIndex, bss, cmock_retval) wifi_connect_CMockExpectAndReturn(__LINE__, apIndex, bss, cmock_retval)
void wifi_connect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, wifi_bss_info_t* bss, INT cmock_to_return);
#define wifi_disconnect_ExpectAndReturn(apIndex, cmock_retval) wifi_disconnect_CMockExpectAndReturn(__LINE__, apIndex, cmock_retval)
void wifi_disconnect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, INT cmock_to_return);
#define wifi_staConnectionStatus_callback_register_Expect(callback_proc) wifi_staConnectionStatus_callback_register_CMockExpect(__LINE__, callback_proc)
void wifi_staConnectionStatus_callback_register_CMockExpect(UNITY_LINE_TYPE cmock_line, wifi_staConnectionStatus_callback callback_proc);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
