/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKWIFI_HAL_TELEMETRY_H
#define _MOCKWIFI_HAL_TELEMETRY_H

#include "unity.h"
#include "wifi_hal_telemetry.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockwifi_hal_telemetry_Init(void);
void Mockwifi_hal_telemetry_Destroy(void);
void Mockwifi_hal_telemetry_Verify(void);




#define wifi_getRadioBandUtilization_ExpectAndReturn(radioIndex, output_percentage, cmock_retval) wifi_getRadioBandUtilization_CMockExpectAndReturn(__LINE__, radioIndex, output_percentage, cmock_retval)
void wifi_getRadioBandUtilization_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT radioIndex, INT* output_percentage, INT cmock_to_return);
#define wifi_getApAssociatedDeviceDiagnosticResult3_ExpectAndReturn(apIndex, associated_dev_array, output_array_size, cmock_retval) wifi_getApAssociatedDeviceDiagnosticResult3_CMockExpectAndReturn(__LINE__, apIndex, associated_dev_array, output_array_size, cmock_retval)
void wifi_getApAssociatedDeviceDiagnosticResult3_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, wifi_associated_dev3_t** associated_dev_array, UINT* output_array_size, INT cmock_to_return);
#define wifi_getApAssociatedClientDiagnosticResult_ExpectAndReturn(apIndex, mac_addr, dev_conn, cmock_retval) wifi_getApAssociatedClientDiagnosticResult_CMockExpectAndReturn(__LINE__, apIndex, mac_addr, dev_conn, cmock_retval)
void wifi_getApAssociatedClientDiagnosticResult_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT apIndex, mac_address_t mac_addr, wifi_associated_dev3_t* dev_conn, INT cmock_to_return);
#define wifi_getRadioTrafficStats2_ExpectAndReturn(radioIndex, output_struct, cmock_retval) wifi_getRadioTrafficStats2_CMockExpectAndReturn(__LINE__, radioIndex, output_struct, cmock_retval)
void wifi_getRadioTrafficStats2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT radioIndex, wifi_radioTrafficStats2_t* output_struct, INT cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
