/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKWIFI_HAL_RADIO_H
#define _MOCKWIFI_HAL_RADIO_H

#include "unity.h"
#include "wifi_hal_radio.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockwifi_hal_radio_Init(void);
void Mockwifi_hal_radio_Destroy(void);
void Mockwifi_hal_radio_Verify(void);




#define wifi_getRadioTransmitPower_ExpectAndReturn(radioIndex, output_ulong, cmock_retval) wifi_getRadioTransmitPower_CMockExpectAndReturn(__LINE__, radioIndex, output_ulong, cmock_retval)
void wifi_getRadioTransmitPower_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT radioIndex, ULONG* output_ulong, INT cmock_to_return);
#define wifi_getRadioOperatingChannelBandwidth_ExpectAndReturn(radioIndex, output_string, cmock_retval) wifi_getRadioOperatingChannelBandwidth_CMockExpectAndReturn(__LINE__, radioIndex, output_string, cmock_retval)
void wifi_getRadioOperatingChannelBandwidth_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, INT radioIndex, CHAR* output_string, INT cmock_to_return);
#define wifi_setRadioOperatingParameters_ExpectAndReturn(index, operationParam, cmock_retval) wifi_setRadioOperatingParameters_CMockExpectAndReturn(__LINE__, index, operationParam, cmock_retval)
void wifi_setRadioOperatingParameters_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, wifi_radio_index_t index, wifi_radio_operationParam_t* operationParam, INT cmock_to_return);
#define wifi_scanResults_callback_register_Expect(callback_proc) wifi_scanResults_callback_register_CMockExpect(__LINE__, callback_proc)
void wifi_scanResults_callback_register_CMockExpect(UNITY_LINE_TYPE cmock_line, wifi_scanResults_callback callback_proc);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
